theme: jekyll-theme-cayman
title: Attentional Learn-able Pooling for Human Activity Recognition
description: IEEE International Conference on Robotics and Automation (ICRA) 2021
github:
  is_project_page: false
